### ISSUE TITLE
Collapsible tableContent

### ISSUE THREAD

**Issue by jordannakamoto** [mongo-express/mongo-express#394] opened 2018-03-12 19:40 UTC
For some reason my installation of mongo-express had issues displaying nested objects.

I tried to edit these lines from filter.js  
```
if (typeof input === 'object' && input.toString().substr(0, 15) === '[object Object]') {
    return '<pre>' + entifyGTLTAmp(JSON.stringify(input, null, 2)) + '</pre>';
  }
```

It seemed that this was being skipped because my objects were strings. So I found stringDocIDs() and removed the default switch.
```

exports.stringDocIDs = function (input) {

  // Turns {_bsontype: ' ObjectID', id:12345... } into a plain string
  if (input && typeof input === 'object') {
    switch (input._bsontype) {
      case 'Binary':
        return input.toJSON();
      case 'ObjectID':
        return input.toString();
    }
  }

  return input;
};
```

Seems to work now. What went wrong?

**Comment by Codelica** [comment] 2018-05-24 19:36
I'm seeing the same thing (using the Docker image).  Looks like the commit to fix this has been made:

https://github.com/mongo-express/mongo-express/commit/cc5b3abc11dd20cfcc72eb2371e141a3e8b6d392#diff-b3ba42190a1a08de7bbd394b00bafab6

But at least in my case, the problem is the docker image hasn't been updated (it's still using v0.45)

**Comment by dozoisch** [comment] 2018-06-28 19:45
Seems like this has been fixed on latest version.

**Closed by dozoisch** 2018-06-28 19:45 UTC
