### ISSUE TITLE
Installation issue with NPM

### ISSUE THREAD

**Issue by codernirdesh** [mongo-express/mongo-express#1565] opened 2024-06-10 05:00 UTC
While doing `npm i -g mongo-express` i'm getting the following error. I've also attached the node and npm version here.

```terminal
$ npm install -g mongo-express
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "patch:": patch:mongodb-query-parser@npm%3A2.4.6#~/.yarn/patches/mongodb-query-parser-npm-2.4.6-234abad2fc.patch

npm error A complete log of this run can be found in: /home/nirdesh/.npm/_logs/2024-06-10T04_50_37_208Z-debug-0.log
```

## Error Log
```text
nirdesh at server in ~
$ cat /home/nirdesh/.npm/_logs/2024-06-10T04_50_37_208Z-debug-0.log
0 verbose cli /home/nirdesh/.local/share/fnm/node-versions/v22.2.0/installation/bin/node /run/user/1000/fnm_multishells/58565_1717994893910/bin/npm
1 info using npm@10.7.0
2 info using node@v22.2.0
3 silly config:load:file:/home/nirdesh/.local/share/fnm/node-versions/v22.2.0/installation/lib/node_modules/npm/npmrc
4 silly config:load:file:/home/nirdesh/.npmrc
5 silly config:load:file:/home/nirdesh/.local/share/fnm/node-versions/v22.2.0/installation/etc/npmrc
6 verbose title npm install mongo-express
7 verbose argv "install" "--global" "mongo-express"
8 verbose logfile logs-max:10 dir:/home/nirdesh/.npm/_logs/2024-06-10T04_50_37_208Z-
9 verbose logfile /home/nirdesh/.npm/_logs/2024-06-10T04_50_37_208Z-debug-0.log
10 silly logfile start cleaning logs, removing 1 files
11 silly logfile done cleaning log files
12 silly idealTree buildDeps
13 silly fetch manifest mongo-express@*
14 http fetch GET 200 https://registry.npmjs.org/mongo-express 1190ms (cache revalidated)
15 silly placeDep ROOT mongo-express@1.0.2 OK for:  want: *
16 silly fetch manifest basic-auth-connect@^1.0.0
17 silly fetch manifest body-parser@^1.20.1
18 silly fetch manifest bootstrap-paginator@github:rtritto/bootstrap-paginator#develop
19 http fetch GET 200 https://registry.npmjs.org/body-parser 23ms (cache hit)
20 silly fetch manifest bson@^4.7.0
21 http fetch GET 200 https://registry.npmjs.org/bson 9ms (cache hit)
22 silly fetch manifest busboy@^1.6.0
23 http fetch GET 200 https://registry.npmjs.org/basic-auth-connect 132ms (cache revalidated)
24 silly fetch manifest cli-color@^2.0.3
25 http fetch GET 200 https://registry.npmjs.org/busboy 343ms (cache revalidated)
26 silly fetch manifest commander@^2.9.0
27 http fetch GET 200 https://registry.npmjs.org/commander 142ms (cache revalidated)
28 silly fetch manifest cookie-parser@1.4.6
29 http fetch GET 200 https://registry.npmjs.org/cli-color 1091ms (cache revalidated)
30 silly fetch manifest csurf@1.11.0
31 http fetch GET 200 https://registry.npmjs.org/csurf 164ms (cache revalidated)
32 silly fetch manifest dotenv@^16.0.3
33 http fetch GET 200 https://registry.npmjs.org/dotenv 59ms (cache revalidated)
34 silly fetch manifest errorhandler@1.5.1
35 http fetch GET 200 https://registry.npmjs.org/cookie-parser 906ms (cache revalidated)
36 silly fetch manifest express@^4.18.2
37 http fetch GET 200 https://registry.npmjs.org/express 9ms (cache hit)
38 silly fetch manifest express-fileupload@^1.4.0
39 http fetch GET 200 https://registry.npmjs.org/errorhandler 87ms (cache revalidated)
40 silly fetch manifest express-session@^1.17.3
41 http fetch GET 200 https://registry.npmjs.org/express-fileupload 831ms (cache revalidated)
42 silly fetch manifest flat@^5.0.2
43 http fetch GET 200 https://registry.npmjs.org/express-session 887ms (cache revalidated)
44 silly fetch manifest free-swig@^1.5.2
45 http fetch GET 200 https://registry.npmjs.org/flat 274ms (cache revalidated)
46 silly fetch manifest gridfs-stream@^1.1.1
47 http fetch GET 200 https://registry.npmjs.org/gridfs-stream 802ms (cache revalidated)
48 silly fetch manifest html-entities@^2.3.3
49 http fetch GET 200 https://registry.npmjs.org/free-swig 1030ms (cache revalidated)
50 silly fetch manifest json2csv@^5.0.7
51 http fetch GET 200 https://registry.npmjs.org/html-entities 80ms (cache revalidated)
52 silly fetch manifest lodash-es@^4.17.21
53 http fetch GET 200 https://registry.npmjs.org/lodash-es 132ms (cache revalidated)
54 silly fetch manifest memorystore@^1.6.7
55 http fetch GET 200 https://registry.npmjs.org/json2csv 823ms (cache revalidated)
56 silly fetch manifest method-override@^3.0.0
57 http fetch GET 200 https://registry.npmjs.org/method-override 114ms (cache revalidated)
58 silly fetch manifest mongodb@^4.13.0
59 http fetch GET 200 https://registry.npmjs.org/mongodb 14ms (cache hit)
60 verbose stack Error: Unsupported URL Type "patch:": patch:mongodb-query-parser@npm%3A2.4.6#~/.yarn/patches/mongodb-query-parser-npm-2.4.6-234abad2fc.patch
60 verbose stack     at unsupportedURLType (/home/nirdesh/.local/share/fnm/node-versions/v22.2.0/installation/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:310:15)
60 verbose stack     at fromURL (/home/nirdesh/.local/share/fnm/node-versions/v22.2.0/installation/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:367:13)
60 verbose stack     at Function.resolve (/home/nirdesh/.local/share/fnm/node-versions/v22.2.0/installation/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:83:12)
60 verbose stack     at /home/nirdesh/.local/share/fnm/node-versions/v22.2.0/installation/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1026:39
60 verbose stack     at run (/home/nirdesh/.local/share/fnm/node-versions/v22.2.0/installation/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:67:22)
60 verbose stack     at /home/nirdesh/.local/share/fnm/node-versions/v22.2.0/installation/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:79:13
61 verbose cwd /home/nirdesh
62 verbose Linux 6.8.11-300.fc40.x86_64
63 verbose node v22.2.0
64 verbose npm  v10.7.0
65 error code EUNSUPPORTEDPROTOCOL
66 error Unsupported URL Type "patch:": patch:mongodb-query-parser@npm%3A2.4.6#~/.yarn/patches/mongodb-query-parser-npm-2.4.6-234abad2fc.patch
67 verbose exit 1
68 verbose code 1
69 silly unfinished npm timer command:install 1717995037587
70 silly unfinished npm timer reify 1717995037589
71 silly unfinished npm timer reify:loadTrees 1717995037595
72 silly unfinished npm timer idealTree 1717995037596
73 silly unfinished npm timer idealTree:buildDeps 1717995037609
74 silly unfinished npm timer idealTree:#root 1717995037609
75 error A complete log of this run can be found in: /home/nirdesh/.npm/_logs/2024-06-10T04_50_37_208Z-debug-0.log
```

The same package works with Yarn. By doing `yarn global add mongo-express`

-------------------------------------------
Node Version : 
```bash
$ node --version
v22.2.0
```

NPM version : 
```bash
$ npm --version
10.7.0
```

**Comment by rtritto** [comment] 2024-06-10 11:55
Duplicate of #1317 #1362
Fixed in #1255
Npm pacakge needs to be updated.
Until that, you can instead use main branch.

**Closed by rtritto** 2024-06-10 11:55 UTC
Labels: old_npm_version
