### ISSUE TITLE
Cant use SSL

### ISSUE THREAD

**Issue by Amer1canDream** [mongo-express/mongo-express#452] opened 2019-01-14 10:25 UTC
Run docker container with parametrs:

 -e ME_CONFIG_SITE_SSL_ENABLED="true"  -e ME_CONFIG_SITE_SSL_CRT_PATH="/path/to/mongo.crt" -e ME_CONFIG_SITE_SSL_KEY_PATH="/path/to/mongo.key"

i get an error:
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open '/path/to/mongo.key'

but file is exist. i tried to use chmod 777 but the error did not disappear. What am I doing wrong?

**Comment by SleepyDeb** [comment] 2024-12-19 02:23
I can't reproduce this.

@rtritto close it

**Closed** 2024-12-19 08:44 UTC
